project_id = "fkviagopdmfytphpwtha"

[functions.save-api-key]
verify_jwt = true

[functions.create-user]
verify_jwt = true

[functions.change-user-password]
verify_jwt = true

[functions.whatsapp-session]
verify_jwt = true

[functions.whatsapp-send-message]
verify_jwt = true